export interface ProjectEntity {
  Id: string ,
  Title:  string   ,
 Description :  string   ,
  StartDate :  Date   ,
  EndDate :  Date   ,
  Budget :  number   ,
  Cost :  number   ,
  Rating :  number   ,
  Customer :  string   ,
  Status :  string   ,
  Manager :  string  ,
  Tasks :  [] ,
  Team :  [] ,
}
